set(FILE_GROUP_assemble "")
set(FILE_GROUP_assembleWithPreprocess "")
set(FILE_GROUP_compile "../../../../../../Documents/git/CANSART/Controller Library/PIC32/Library/cansart.c;../../../../../../Documents/git/CANSART/Controller Library/PIC32/Library/cansartP.c;../../../../firmware/VCU2.0.X/TorqueControl.c")
set(FILE_GROUP_compile_cpp "")
set(FILE_GROUP_link "")
set(BUILD_LIBRARY 0)
set(internal_image_name "c:/Users/pedro/Documents/GIT/2_FIRMWARE/VCU_Firmware/_build_mplab/VCU_firmware/default/image_default.elf/default.elf")
set(image_name "default.elf")
set(output_dir "c:/Users/pedro/Documents/GIT/2_FIRMWARE/VCU_Firmware/out/VCU_firmware")
