set(CMAKE_C_COMPILER_WORKS 1)
set(MP_CC_DIR "c:/Program Files/Microchip/xc32/v4.35")
set(CMAKE_C_COMPILER "c:/Program Files/Microchip/xc32/v4.35/bin/xc32-gcc.exe")
set(CMAKE_CXX_COMPILER_WORKS 1)
set(MP_CPPC_DIR "c:/Program Files/Microchip/xc32/v4.35")
set(CMAKE_CC_COMPILER "c:/Program Files/Microchip/xc32/v4.35/bin/xc32-g++.exe")
set(MP_AS "c:/Program Files/Microchip/xc32/v4.35/bin/xc32-as.exe")
set(MP_LD "c:/Program Files/Microchip/xc32/v4.35/bin/xc32-ld.exe")
set(MP_BIN2HEX "c:/Program Files/Microchip/xc32/v4.35/bin/xc32-bin2hex.exe")
